apiVersion: v1
kind: Secret
metadata:
  name: projeto-flask-secret
  namespace: default
type: bootstrap.kubernetes.io/token
stringData:
  url-banco: "jdbc:mysql://twizydsvn1:3306/"
  user-banco: "root"
  password-banco: "root"