apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  labels:
    app: flask-app-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-container
        image: danielso2007/flask-kub-projeto:1.0.0
        ports:
        - containerPort: 5000
        env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: projeto-flask-secret
              key: url-banco
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: projeto-flask-secret
              key: user-banco
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: projeto-flask-secret
              key: password-banco              
      volumes:
      - name: flask-volume
        secret:
          secretName: projeto-flask-secret