---
apiVersion: v1
kind: Namespace
metadata:
  name: flask-namespace
  labels:
     name: flask-namespace
---
apiVersion: v1
kind: Secret
metadata:
  name: projeto-flask-secret
  namespace: default
type: bootstrap.kubernetes.io/token
stringData:
  url-banco: "jdbc:mysql://twizydsvn1:3306/"
  user-banco: "root"
  password-banco: "root"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  labels:
    app: flask-app-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-container
        image: danielso2007/flask-kub-projeto:1.0.0
        ports:
        - containerPort: 5000
        env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: projeto-flask-secret
              key: url-banco
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: projeto-flask-secret
              key: user-banco
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: projeto-flask-secret
              key: password-banco   
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: 'TCP'
      port: 5000
      targetPort: 5000
  type: LoadBalancer